name: test

on:
  pull_request:
  push:
      branches:
      - master

jobs:
  mix_test:
    name: mix test (OTP ${{matrix.otp}} | Elixir ${{matrix.elixir}})

    strategy:
      matrix:
        include:
          - elixir: 1.7.4
            otp: 21.3.8.16

          - elixir: 1.8.2
            otp: 21.3.8.16

          - elixir: 1.9.4
            otp: 21.3.8.16

          - elixir: 1.11.4
            otp: 23.3

          - elixir: 1.12.0
            otp: 24.0

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: ${{matrix.elixir}}
        otp-version: ${{matrix.otp}}

    - name: Install Dependencies
      run: mix deps.get --only test

    - name: Run Tests
      run: mix test
